Allow GetHeader to receive (optional) encoding
NetTopologySuite/NetTopologySuite.IO.ShapeFile pull request #13
Opened 2018-09-11 13:02 UTC by frankhommers

GetHeader will always result in DefaultEncoding and will not be usable in a ShapefileDataWriter with a different encoding.

It would be better to make GetHeader non-static and make it use the _encoding of the ShapefileDataWriter itself (but that breaks the API...)

2018-09-11 13:10 UTC, airbreather requested changes

2018-09-11 13:10 UTC, airbreather commented on NetTopologySuite.IO.GeoTools/ShapefileDataWriter.cs
> +        public static DbaseFileHeader GetHeader(IFeature feature, int count, Encoding encoding = null)
> but that breaks the API...

Adding a default parameter is also a breaking change, at least in terms of binary compatibility.

Overload instead?

2018-09-11 13:33 UTC, frankhommers reviewed
Made encoding an overload instead of optional parameter

2018-09-11 15:03 UTC, airbreather approved these changes

2018-09-11 15:03 UTC, merged

2018-09-11 15:04 UTC, airbreather commented
Thank you for your contribution!

2018-09-12 11:02 UTC, frankhommers commented
Thanks!